export const ALL_COMPLAINT_REQUEST = "ALL_COMPLAINT_REQUEST";
export const ALL_COMPLAINT_SUCCESS = "ALL_COMPLAINT_SUCCESS";
export const ALL_COMPLAINT_FAIL = "ALL_COMPLAINT_FAIL";


export const NEW_COMPLAINT_REQUEST = "NEW_COMPLAINT_REQUEST";
export const NEW_COMPLAINT_SUCCESS = "NEW_COMPLAINT_SUCCESS";
export const NEW_COMPLAINT_RESET = "NEW_COMPLAINT_RESET";
export const NEW_COMPLAINT_FAIL = "NEW_COMPLAINT_FAIL";

export const UPDATE_COMPLAINT_REQUEST = "UPDATE_COMPLAINT_REQUEST";
export const UPDATE_COMPLAINT_SUCCESS = "UPDATE_COMPLAINT_SUCCESS";
export const UPDATE_COMPLAINT_RESET = "UPDATE_COMPLAINT_RESET";
export const UPDATE_COMPLAINT_FAIL = "UPDATE_COMPLAINT_FAIL";

export const DELETE_COMPLAINT_REQUEST = "DELETE_COMPLAINT_REQUEST";
export const DELETE_COMPLAINT_SUCCESS = "DELETE_COMPLAINT_SUCCESS";
export const DELETE_COMPLAINT_RESET = "DELETE_COMPLAINT_RESET";
export const DELETE_COMPLAINT_FAIL = "DELETE_COMPLAINT_FAIL";


export const COMPLAINT_DETAILS_REQUEST = "COMPLAINT_DETAILS_REQUEST";
export const COMPLAINT_DETAILS_SUCCESS = "COMPLAINT_DETAILS_SUCCESS";
export const COMPLAINT_DETAILS_FAIL = "COMPLAINT_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";